<?php

namespace App\Providers;

// use Illuminate\Support\Facades\Gate;
use Illuminate\Foundation\Support\Providers\AuthServiceProvider as ServiceProvider;
use Illuminate\Support\Facades\Gate;

class AuthServiceProvider extends ServiceProvider
{
    /**
     * The model to policy mappings for the application.
     *
     * @var array<class-string, class-string>
     */
    protected $policies = [
        //
    ];
    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub

        $this->app->bind('abilities',function () {
            return include base_path('Data/abilities.php');
            });
    }

    /**
     * Register any authentication / authorization services.
     */
    public function boot(): void
    {

        foreach ($this->app->make('abilities') as $key =>$value)
        {
            Gate::define($key,function ($user) use ($key){
                return $user->hasAbility($key);

            });
        }


    }
}
